services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    networks:
      - noteapp-net

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      api:
        condition: service_started
    networks:
      - noteapp-net

networks:
  noteapp-net:
    driver: bridge
